[build]
cmd = "cd backend && npm install && npm run build"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
PORT = "3001"

[environments.staging]
[environments.staging.variables]
NODE_ENV = "staging"
PORT = "3001"